Repository AICoE/data-driven-development, pull requests merged in 2021-06, with the labels that each got.

#2 chore: Add hema to approvers
  OWNERS
Labels: approved, lgtm

#1 rough structure
  README.md
  data-presentation/grafana.md
  data-presentation/jupyter-notebook.md
  data-presentation/superset.md
  data-sources/github.md
  data-sources/google-analytics.md
  data-sources/prometheus.md
  notebooks/prometheus.ipynb
Labels: approved, lgtm, size/M

#9 Add issue templates to repo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/L

#18 Update prow
  .prow.yaml
Labels: approved, lgtm, size/XS

#19 Update README
  README.md
Labels: size/M

#20 Add Prometheus data source guide
  assets/images/anatomy-metric.png
  assets/images/prometheus-timeseries-graph.png
  assets/images/promql-example.png
  data-sources/prometheus.md
Labels: approved, lgtm, size/M
