Repository AICoE/data-driven-development, pull requests merged in 2021-11, with the labels that each got.

#45 Add Kebechet tooling section
  examples/kebechet/README.md
  examples/kebechet/tooling.md
Labels: approved, size/M

#51 Switch to https for precommit config
  .pre-commit-config.yaml
Labels: approved, size/XS

#47 Add Kebechet metrics section
  examples/kebechet/metrics.md
Labels: approved, size/M

#46 Add collecting and storing metrics section
  examples/kebechet/collecting_and_storing_metrics.md
Labels: size/L, approved

#49 Add grafana markdown
  assets/images/gf-add-data-source.png
  assets/images/gf-dashboard.gif
  assets/images/gf-data-source.png
  assets/images/gf-export.png
  assets/images/gf-json.png
  assets/images/gf-panel.gif
  assets/images/gf-query-editor.gif
  data-presentation/grafana.md
Labels: approved, size/M

#52 Add Table of Content for Kebechet
  examples/kebechet/README.md
Labels: approved, size/S

#48 Add Kebechet alerting section
  examples/kebechet/alerting.md
Labels: approved, size/S

#54 Add generic Superset guide
  assets/images/superset-add-dataset.png
  assets/images/superset-add-db.png
  data-presentation/superset.md
Labels: approved, size/M

#55 Update accessing metrics markdown
  examples/kebechet/accessing_metrics.md
Labels: approved, size/XS

#56 Add jupyter book build requirements
  .gitignore
  _config.yml
  _toc.yml
  aicoe-logo.png
Labels: approved, size/M

#58 Update links in grafana doc
  data-presentation/grafana.md
Labels: approved, size/XS, lgtm

#59 Add more Kebechet metrics
  examples/kebechet/metrics.md
Labels: approved, size/XS
